import { foodEight, foodEighteen, foodEleven, foodFifteen, foodFive, foodForty, foodFortyFive, foodFortyFour, foodFortyOne, foodFortyThree, foodFortyTwo, foodFour, foodFourteen, foodNine, foodNineteen, foodOne, foodSeven, foodSeventeen, foodSix, foodSixteen, foodTen, foodThirteen, foodThirty, foodThirtyEight, foodThirtyFive, foodThirtyFour, foodThirtyNine, foodThirtyOne, foodThirtySeven, foodThirtySix, foodThirtyThree, foodThirtyTwo, foodThree, foodTweleve, foodTwenty, foodTwentyEight, foodTwentyFive, foodTwentyFour, foodTwentyNine, foodTwentyOne, foodTwentySeven, foodTwentySix, foodTwentyThree, foodTwentyTwo, foodTwo } from './assets/index'
export const categories = ["All", "Breakfast", "Lunch", "Dinner"];
export const foodCard = [
    {
        name: 'Spaghetti Carbonara',
        img: `${foodOne}`,
        des: "A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper. It's creamy, savory, and perfectly seasoned.",
        price: '20.00',
        type: 'Dinner',
    },
    {
        name: 'Margherita Pizza',
        img: `${foodTwo}`,
        des: "A simple yet delicious pizza topped with fresh mozzarella, tomatoes, and basil. A perfect representation of Italian flavors.",
        price: '18.00',
        type: 'Lunch',
    },
    {
        name: 'Sushi Platter',
        img: `${foodThree}`,
        des: "An assortment of fresh sushi including tuna, salmon, and eel, served with soy sauce, wasabi, and pickled ginger.",
        price: '35.00',
        type: 'Dinner',
    },
    {
        name: 'Caesar Salad',
        img: `${foodFour}`,
        des: "Crisp romaine lettuce tossed in Caesar dressing, topped with croutons, parmesan cheese, and a hint of garlic.",
        price: '12.00',
        type: 'Lunch',
    },
    {
        name: 'BBQ Ribs',
        img: `${foodFive}`,
        des: "Juicy pork ribs slow-cooked and glazed with a sweet and smoky BBQ sauce, served with a side of coleslaw.",
        price: '25.00',
        type: 'Dinner',
    },
    {
        name: 'Pad Thai',
        img: `${foodSix}`,
        des: "A popular Thai dish made with stir-fried rice noodles, tofu, shrimp, peanuts, and a tangy tamarind sauce.",
        price: '22.00',
        type: 'Dinner',
    },
    {
        name: 'Tacos Al Pastor',
        img: `${foodSeven}`,
        des: "Traditional Mexican tacos filled with marinated pork, pineapple, cilantro, and onions, served on soft corn tortillas.",
        price: '15.00',
        type: 'Lunch',
    },
    {
        name: 'Lobster Roll',
        img: `${foodEight}`,
        des: "A New England favorite, this lobster roll is packed with fresh lobster meat, lightly dressed in mayo, served in a buttered roll.",
        price: '28.00',
        type: 'Lunch',
    },
    {
        name: 'Chocolate Lava Cake',
        img: `${foodNine}`,
        des: "A decadent dessert with a warm, gooey chocolate center that flows out when cut, served with vanilla ice cream.",
        price: '10.00',
        type: 'Dinner',
    },
    {
        name: 'Ramen Noodles',
        img: `${foodTen}`,
        des: "A flavorful Japanese noodle soup with a rich broth, tender noodles, soft-boiled eggs, and sliced pork belly.",
        price: '16.00',
        type: 'Dinner',
    },
    {
        name: 'Chicken Parmesan',
        img: `${foodEleven}`,
        des: "Breaded and fried chicken breasts smothered in marinara sauce and melted mozzarella cheese, served over pasta.",
        price: '22.00',
        type: 'Dinner',
    },
    {
        name: 'Shrimp Scampi',
        img: `${foodTweleve}`,
        des: "Juicy shrimp sautéed in a garlic butter sauce, served over a bed of linguine and garnished with fresh parsley.",
        price: '24.00',
        type: 'Dinner',
    },
    {
        name: 'Beef Tacos',
        img: `${foodThirteen}`,
        des: "Crispy taco shells filled with seasoned ground beef, lettuce, tomato, shredded cheese, and a dollop of sour cream.",
        price: '14.00',
        type: 'Lunch',
    },
    {
        name: 'Grilled Salmon',
        img: `${foodFourteen}`,
        des: "Fresh salmon fillets grilled to perfection, served with roasted vegetables and a lemon butter sauce.",
        price: '26.00',
        type: 'Dinner',
    },
    {
        name: 'Chicken Wings',
        img: `${foodFifteen}`,
        des: "Crispy chicken wings tossed in your choice of sauce: buffalo, BBQ, or garlic parmesan, served with celery and ranch.",
        price: '18.00',
        type: 'Lunch',
    },
    {
        name: 'Pancakes',
        img: `${foodSixteen}`,
        des: "Fluffy pancakes served with maple syrup and fresh berries.",
        price: '10.00',
        type: 'Breakfast',
    },
    {
        name: 'Croissant',
        img: `${foodSeventeen}`,
        des: "Buttery, flaky croissants perfect for breakfast with a cup of coffee.",
        price: '5.00',
        type: 'Breakfast',
    },
    {
        name: 'Eggs Benedict',
        img: `${foodEighteen}`,
        des: "Poached eggs on English muffins topped with hollandaise sauce.",
        price: '12.00',
        type: 'Breakfast',
    },
    {
        name: 'French Toast',
        img: `${foodNineteen}`,
        des: "Thick slices of bread soaked in egg mixture and fried until golden.",
        price: '9.00',
        type: 'Breakfast',
    },
    {
        name: 'Quiche Lorraine',
        img: `${foodTwenty}`,
        des: "Savory pie filled with eggs, cream, cheese, and bacon.",
        price: '14.00',
        type: 'Breakfast',
    },
    {
        name: 'Chow Mein',
        img: `${foodTwentyOne}`,
        des: "Stir-fried noodles with vegetables and meat in a soy sauce.",
        price: '16.00',
        type: 'Lunch',
    },
    {
        name: 'Biryani',
        img: `${foodTwentyTwo}`,
        des: "Fragrant rice dish with spices, meat, and vegetables.",
        price: '18.00',
        type: 'Dinner',
    },
    {
        name: 'Paella',
        img: `${foodTwentyThree}`,
        des: "A traditional Spanish rice dish cooked with seafood and saffron.",
        price: '30.00',
        type: 'Dinner',
    },
    {
        name: 'Goulash',
        img: `${foodTwentyFour}`,
        des: "A hearty stew of meat and vegetables seasoned with paprika.",
        price: '15.00',
        type: 'Dinner',
    },
    {
        name: 'Falafel',
        img: `${foodTwentyFive}`,
        des: "Crispy fried balls of ground chickpeas, served with tahini sauce.",
        price: '12.00',
        type: 'Lunch',
    },
    {
        name: 'Chili Con Carne',
        img: `${foodTwentySix}`,
        des: "Spicy stew with meat, beans, and chili peppers.",
        price: '14.00',
        type: 'Dinner',
    },
    {
        name: 'Tom Yum Soup',
        img: `${foodTwentySeven}`,
        des: "Spicy and sour Thai soup with shrimp and mushrooms.",
        price: '11.00',
        type: 'Lunch',
    },
    {
        name: 'Beef Stroganoff',
        img: `${foodTwentyEight}`,
        des: "Tender beef cooked in a creamy sauce served over noodles.",
        price: '19.00',
        type: 'Dinner',
    },
    {
        name: 'Tandoori Chicken',
        img: `${foodTwentyNine}`,
        des: "Marinated chicken grilled in a traditional tandoor oven.",
        price: '20.00',
        type: 'Dinner',
    },
    {
        name: 'Vegetable Curry',
        img: `${foodThirty}`,
        des: "A flavorful curry made with seasonal vegetables and spices.",
        price: '14.00',
        type: 'Dinner',
    },
    {
        name: 'Ceviche',
        img: `${foodThirtyOne}`,
        des: "Fresh fish marinated in lime juice, mixed with onions and cilantro.",
        price: '16.00',
        type: 'Lunch',
    },
    {
        name: 'Kebabs',
        img: `${foodThirtyTwo}`,
        des: "Grilled skewers of marinated meat served with flatbread.",
        price: '17.00',
        type: 'Dinner',
    },
    {
        name: 'Lentil Soup',
        img: `${foodThirtyThree}`,
        des: "Hearty soup made with lentils and vegetables, seasoned to perfection.",
        price: '10.00',
        type: 'Lunch',
    },
    {
        name: 'Nasi Goreng',
        img: `${foodThirtyFour}`,
        des: "Indonesian fried rice served with vegetables, shrimp, and a fried egg on top.",
        price: '12.00',
        type: 'Lunch',
    },
    {
        name: 'Moussaka',
        img: `${foodThirtyFive}`,
        des: "A Greek casserole made with layers of eggplant, minced meat, and béchamel sauce.",
        price: '18.00',
        type: 'Dinner',
    },
    {
        name: 'Ratatouille',
        img: `${foodThirtySix}`,
        des: "A French vegetable dish made with zucchini, eggplant, peppers, and tomatoes.",
        price: '16.00',
        type: 'Dinner',
    },
    {
        name: 'Hummus and Pita',
        img: `${foodThirtySeven}`,
        des: "Creamy chickpea dip served with warm pita bread.",
        price: '8.00',
        type: 'Lunch',
    },
    {
        name: 'Chimichurri Steak',
        img: `${foodThirtyEight}`,
        des: "Grilled steak topped with a zesty chimichurri sauce.",
        price: '24.00',
        type: 'Dinner',
    },
    {
        name: 'Banh Mi',
        img: `${foodThirtyNine}`,
        des: "Vietnamese sandwich made with pork, pickled vegetables, and herbs in a baguette.",
        price: '10.00',
        type: 'Lunch',
    },
    {
        name: 'Pesto Pasta',
        img: `${foodForty}`,
        des: "Pasta tossed in a rich basil pesto sauce and topped with parmesan.",
        price: '15.00',
        type: 'Lunch',
    },
    {
        name: 'Samosas',
        img: `${foodFortyOne}`,
        des: "Deep-fried pastries filled with spiced potatoes and peas.",
        price: '7.00',
        type: 'Lunch',
    },
    {
        name: 'Shakshuka',
        img: `${foodFortyTwo}`,
        des: "Poached eggs in a spicy tomato sauce with peppers and onions.",
        price: '12.00',
        type: 'Breakfast',
    },
    {
        name: 'Rogan Josh',
        img: `${foodFortyThree}`,
        des: "A flavorful curry made with tender lamb cooked in spices and yogurt.",
        price: '20.00',
        type: 'Dinner',
    },
    {
        name: 'Cottage Pie',
        img: `${foodFortyFour}`,
        des: "A meat pie with a crust of mashed potatoes, traditionally made with ground beef.",
        price: '16.00',
        type: 'Dinner',
    },
    {
        name: 'Stuffed Bell Peppers',
        img: `${foodFortyFive}`,
        des: "Bell peppers filled with rice, meat, and spices, then baked.",
        price: '14.00',
        type: 'Dinner',
    },
];
